config_examples.api_config:
  title: 'Example API Configuration'
  description: 'Configure the example API settings.'
  route_name: config_examples.api_config
  parent: system.admin_config_services
  menu_name: admin